name: panel-jstree-test
channels:
  - pyviz
  - pyviz/label/dev
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - panel<1
  - conda-forge::nodejs>=14
  - conda-forge::jupyterlab
  - pip
  - pip:
      - -e .
