name: panel-jstree
channels:
  - pyviz
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - bokeh<3
  - pyviz::panel<1.0
  - pyviz::param<2.0
  - conda-forge::nodejs>=14
  - conda-forge::jupyterlab
  - pip
