name: panel-jstree
channels:
  - pyviz
  - pyviz/label/dev
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - panel>=1.3
  - conda-forge::nodejs>=14
  - black
  - isort
  - pip
  - pip:
      - -e .
